﻿@startuml "Domain"
skin rose

Sim --> "8" Need : one per type
Need <|-- Hunger
Need <|-- Social
Need <|-- Fun
Need <|-- Comfort
Need <|-- Hygiene
Need <|-- Bladder
Need <|-- Room
Need <|-- Energy

Action --> "0..*" Need : satisfies
Time --> Need : affects
Sim --> Action : perform

Lot --> "0..*" Sim
Lot --> "0..*" Building
Lot --> "0..*" Furniture
Lot -->"0..*" Item

Furniture --> "0..*" Action : offers
Item --> "0..*" Action : offers

@enduml