@startuml "Movement"
skin rose

boundary Input
control Control 

Input -> Control : MoveTo(point)
Control -> Control : GetActiveSim()
Control -> Sim : Command(Action.MoveTo(point))
Sim --> Control

...

Sim -> Sim : Perform(Action.MoveTo(point))
Sim --> Control : <<Event>> \n MovingTowards(point)

loop WillingToMove(sim, point) \n    && !IsThereYet(sim, point) \n    && CanMove(sim)
    Control -> Control : MoveTowards(sim, point)
end

@enduml